[package]
name = "lil-owo-bootstrap"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faerie = "0.16.0"
goblin = "0.4.2"
target-lexicon = "0.11.0"
